/* Generated By:JavaCC: Do not edit this line. CompilerTreeConstants.java Version 5.0 */
package parser;

@SuppressWarnings("all")
public interface CompilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTSENTENCEBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTDECLARATION = 4;
  public int JJTASSIGN = 5;
  public int JJTARRAY = 6;
  public int JJTFACTOR = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTIF = 9;
  public int JJTSWITCH = 10;
  public int JJTDO_WHILE = 11;
  public int JJTWHILE = 12;
  public int JJTWHILE_CONDITION = 13;
  public int JJTFOR = 14;
  public int JJTCONDITION = 15;
  public int JJTEXPRESSION = 16;
  public int JJTTERM = 17;
  public int JJTTYPE = 18;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "SentenceBlock",
    "Statement",
    "declaration",
    "Assign",
    "Array",
    "Factor",
    "assignment",
    "If",
    "Switch",
    "do_while",
    "While",
    "While_Condition",
    "For",
    "Condition",
    "Expression",
    "Term",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=f25520ef22b33ec0f3c8ad2666d56fd5 (do not edit this line) */
