/* Generated By:JJTree&JavaCC: Do not edit this line. Compiler.java */
package parser;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;
import java.util.*;

@SuppressWarnings("all")
public class Compiler/*@bgen(jjtree)*/implements CompilerTreeConstants, CompilerConstants {/*@bgen(jjtree)*/
  protected JJTCompilerState jjtree = new JJTCompilerState();
        public static int count=0; //四元式标�?
        public static int ncount=0; //临时变量下标
        public static int con;
        public static int j=0;
        public static FileOutputStream foutStream ;
        public static PrintStream print_Stream;
        public static ArrayList<MyNode> mylist=new ArrayList<MyNode>();//结点集合
        public static ArrayList<QTInfo> myQTInfo=new ArrayList<QTInfo>(); //四元�?
        public static QTTable table=new QTTable(myQTInfo);//四元式链表，用来存储结果
        public static NodeList   myNodeList=new NodeList(mylist);//封装结点集合，对结点进行处理


//四元式表  
    public static void QTInfoTable()
  {
        try{
           FileOutputStream out=new FileOutputStream("Systable.txt");
           PrintStream QTInfoprint=new PrintStream(out);
           //temp：遍历四元式列表并打�?
           for(QTInfo temp:myQTInfo)
           {
                  QTInfoprint.print(temp);
           }
            QTInfoprint.close();
           out.close();
          }
          catch(IOException e)
          {
                e.printStackTrace();
          }

  }


//词法分析，输�?单词自身值，单词种别>二元�?
  public static void WordAnalysis()
  {
        try{
        SimpleCharStream jj_input_stream=new SimpleCharStream(new FileInputStream(GUI.show.sf));
                CompilerTokenManager tokenManage=new CompilerTokenManager(jj_input_stream);
                FileOutputStream out=new FileOutputStream("WordAnalysis.txt");
                PrintStream wordprint=new PrintStream(out);
                ArrayList<Word> wordlist=new ArrayList<Word>();
                while(true)
                {
                        //读取下一单词
                        Token t=tokenManage.getNextToken();
                        if(t.kind==0)//源文件结束，跳出循环
                        {
                                break;
                        }
                        else
                        {//将单词信息封装在word里存�?
                        Word w = new Word();
                        w.setKind(t.kind);
                        w.setName(t.image);
                    wordlist.add(w);
                        }
                }
                //遍历，打印二元式
                for(Word temp:wordlist)
                {
                        wordprint.print(temp);
                }
                wordprint.close();
                out.close();
        }
        catch(Exception e)
        {
                e.printStackTrace();
        }

  }

//�?��
  final public SimpleNode Start() throws ParseException {
                      /*@bgen(jjtree) Start */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
        Procedure();
        jj_consume_token(0);
                      jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
         {if (true) return jjtn000;}
        break;
      case 0:
        jj_consume_token(0);
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
              {if (true) return jjtn000;}
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//<程序〉→ void main() {〈语句块〉}
  final public void Procedure() throws ParseException {
                  /*@bgen(jjtree) Procedure */
  SimpleNode jjtn000 = new SimpleNode(JJTPROCEDURE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VOID);
      jj_consume_token(MAIN);
      jj_consume_token(LC);
      jj_consume_token(RC);
      SentenceBlock();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//〈语句块〉→{〈语句串〉}
  final public void SentenceBlock() throws ParseException {
                      /*@bgen(jjtree) SentenceBlock */
  SimpleNode jjtn000 = new SimpleNode(JJTSENTENCEBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LB);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
        case WHILE:
        case DO:
        case FOR:
        case SWITCH:
        case FLOAT:
        case LONG:
        case SHORT:
        case INT:
        case CHAR:
        case DOUBLE:
        case SELFPLUS:
        case SELFMINUS:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_1;
        }
        Statement();
      }
      jj_consume_token(RB);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//〈语句串〉→〈赋值语句�?|〈条件语句�?|〈循环语句�?�?....
  final public void Statement() throws ParseException {
                  /*@bgen(jjtree) Statement */
  SimpleNode jjtn000 = new SimpleNode(JJTSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FLOAT:
      case LONG:
      case SHORT:
      case INT:
      case CHAR:
      case DOUBLE:
        declaration();
        break;
      case SELFPLUS:
      case SELFMINUS:
      case IDENTIFIER:
        assignment();
        break;
      case IF:
        If();
        break;
      case SWITCH:
        Switch();
        break;
      case WHILE:
        While();
        break;
      case DO:
        do_while();
        break;
      case FOR:
        For();
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//声明语句（岳冠桥�?
  final public void declaration() throws ParseException {
 /*@bgen(jjtree) declaration */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String type;//变量类型
  MyNode tempnode=null;//在符号表建立tempnode节点，存储变量全部信�?
  Token node;//单词
  String name;//变量名称
  int D=0;
    try {
      type = Type();
      node = jj_consume_token(IDENTIFIER);
                name=node.image;
                //�?��标示符是否已定义，若是则报错，�?出程�?
                if(myNodeList!=null)
                {
                        if(myNodeList.isExientence(name))
                        {
                          String s = "number "+node.beginLine+"  variable \u005c""+name+"\u005c" already exist";
                JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);
                        }
                }
                tempnode=new MyNode(name,type);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LM:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        jj_consume_token(LM);
                D++;
                tempnode.D  = D;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CONSTANT:
          node = jj_consume_token(CONSTANT);
                if(D==1)//若为�?��数组，设置行长度
                {
                        int row=Integer.parseInt(node.image);
                        tempnode.row = row;
                        tempnode.a=new int[row];
                        tempnode.rflag=1;
                }
                else if(D==2)//若为二维数组，设置列长度
                {
                        int col=Integer.parseInt(node.image);
                        tempnode.col = col;
                        tempnode.a=null;
                        tempnode.b=new int[tempnode.row][col];
                        tempnode.cflag=1;
                }
          break;
        default:
          jj_la1[4] = jj_gen;
          ;
        }
        jj_consume_token(RM);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGNMENT:
        Assign(tempnode);
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
                myNodeList.addNode(tempnode);
                D=0;
                node=null;
                tempnode=null;
                name=null;
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DOT:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_3;
        }
        jj_consume_token(DOT);
        node = jj_consume_token(IDENTIFIER);
                name=node.image;
                if(myNodeList!=null)
                {
                        if(myNodeList.isExientence(name))
                        {
                          String s = "number "+node.beginLine+"  variable \u005c""+name+"\u005c" already exist";
                           JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                        }
                }
                tempnode=new MyNode(name,type);
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case LM:
            ;
            break;
          default:
            jj_la1[7] = jj_gen;
            break label_4;
          }
          jj_consume_token(LM);
                D++;
                tempnode.D = D;
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case CONSTANT:
            node = jj_consume_token(CONSTANT);
            if(D==1)
                {
                        int row=Integer.parseInt(node.image);
                        tempnode.row = row;
                        tempnode.a=new int[row];
                        tempnode.rflag=1;
                }
                else if(D==2)
                {
                        int col=Integer.parseInt(node.image);
                        tempnode.col = col;
                        tempnode.a=null;
                        tempnode.b=new int[tempnode.row][col];
                        tempnode.cflag=1;
                }
            break;
          default:
            jj_la1[8] = jj_gen;
            ;
          }
          jj_consume_token(RM);
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ASSIGNMENT:
          Assign(tempnode);
          break;
        default:
          jj_la1[9] = jj_gen;
          ;
        }
                myNodeList.addNode(tempnode);
                D=0;
                tempnode=null;
                node=null;
                name=null;
      }
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//赋�?语句（杨帅）
  final public void Assign(MyNode tempnode) throws ParseException {
 /*@bgen(jjtree) Assign */
        SimpleNode jjtn000 = new SimpleNode(JJTASSIGN);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Record temp;//临时变量
        String st;//下标临时标记
        int value; //变量的�?
        int i=0;
        int j=0;
        String lon;
        int row,col;
        int nr=0;
    try {
      jj_consume_token(ASSIGNMENT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LC:
      case IDENTIFIER:
      case CONSTANT:
        temp = Factor();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                value=Integer.parseInt(temp.getValue());
                tempnode.result=value;
                count++;
                QTTable.addQTInfo(new QTInfo(count,"=",temp.getName(),"-",tempnode.name));
        break;
      case LB:
        jj_consume_token(LB);
ArrayList<Integer> list=new ArrayList<Integer>();//用一�?/ArrayList<Integer>连续接收后面大括号内的�?，待扫描完毕后，�?/修改tempnode并生成相应的四元式�?

        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LC:
        case IDENTIFIER:
        case CONSTANT:
          temp = Factor();
            if(tempnode.rflag==1&&nr>=tempnode.row)
            {
                        String s  = "number "+" Index out of array!! "+tempnode.name;//行越界报错�?
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);
            }
            nr++;//如果不报错，则行++
                value=Integer.parseInt(temp.getValue());
                list.add(value);
          label_5:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case DOT:
              ;
              break;
            default:
              jj_la1[10] = jj_gen;
              break label_5;
            }
            jj_consume_token(DOT);
            temp = Factor();
                if(tempnode.rflag==1&&nr>=tempnode.row)
            {
                        String s = "number "+" Index out of array!! "+tempnode.name;//越界报错
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);
            }
            nr++;
                value=Integer.parseInt(temp.getValue());
                list.add(value);
          }
                if(tempnode.rflag==0)//修改定义标记
                {
                   tempnode.rflag=1;
                   tempnode.row = nr;
                   tempnode.a=new int[nr];
                }
                st="T"+(ncount);
                ncount++;
                count++;
                QTTable.addQTInfo(new QTInfo(count,"=",0+"","-",st));
                Iterator it=list.iterator();//迭代取list里的数放�?/tempnode.a数组里�?
                while(it.hasNext())
                {
                        tempnode.a[i]=(Integer)it.next();
                count++;
                    QTTable.addQTInfo(new QTInfo(count,"[]=",tempnode.a[i]+"","-",tempnode.name+"["+st+"]"));//存数
                    i++;
                    lon=st;
                    if(it.hasNext())
                    {
                    st="T"+(ncount);
                    ncount++;
                    count++;
                    QTTable.addQTInfo(new QTInfo(count,"+",lon,4+"",st));
                    }
                }
          break;
        case LB:
          Array(tempnode,j++,list);
          label_6:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case DOT:
              ;
              break;
            default:
              jj_la1[11] = jj_gen;
              break label_6;
            }
            jj_consume_token(DOT);
            Array(tempnode,j++,list);
          }
                        if(tempnode.rflag==0)
                {
                        tempnode.rflag=1;
                        tempnode.row = j;
                        tempnode.b=new int [tempnode.row][tempnode.col];
                }
                i=0;j=0;int co=0;
                st="T"+(ncount);
                ncount++;
                count++;
                QTTable.addQTInfo(new QTInfo(count,"=",0+"","-",st));//存数//�?��
                Iterator ait=list.iterator();
                while(ait.hasNext())
                {
                        tempnode.b[i][j]=(Integer)ait.next();
                        count++;
                    QTTable.addQTInfo(new QTInfo(count,"[]=",tempnode.b[i][j]+"","-",tempnode.name+"["+st+"]"));
                    lon=st;
                    if(ait.hasNext()){
                    st="T"+(ncount);
                    ncount++;
                    count++;
                    QTTable.addQTInfo(new QTInfo(count,"+",lon,4+"",st));
                    }
                        j++;
                        co++;
                        if(co%tempnode.col==0)//读完�?��后，继续读下�?��
                        {
                                i++;
                                j=0;
                        }
                }
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(RB);
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//二维数组赋�?（宁林）
  final public void Array(MyNode tempnode,int row,ArrayList<Integer> list) throws ParseException {
 /*@bgen(jjtree) Array */
        SimpleNode jjtn000 = new SimpleNode(JJTARRAY);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Record temp;
        int value;
        int i=0;
        int nr=0;
        int cl;
    try {
      jj_consume_token(LB);
                if(tempnode.rflag==1&&row>=tempnode.row)//行越界报�?
                {
                        String s = "number "+" Row Index out of array!! "+tempnode.name;
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                }
      temp = Factor();
            if(tempnode.cflag==1&&nr>=tempnode.col)
            {
                        String s = "number "+" Col Index out of array!! "+tempnode.name;
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

            }
            nr++;
                value=Integer.parseInt(temp.getValue());
                list.add(value);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DOT:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_7;
        }
        jj_consume_token(DOT);
        temp = Factor();
            if(tempnode.cflag==1&&nr>=tempnode.col)//列越界报�?
            {
                        String s = "number "+" Col Index out of array!! "+tempnode.name;
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);
            }
            nr++;
                value=Integer.parseInt(temp.getValue());
                list.add(value);
      }
                if(tempnode.cflag==0)
                {
                   tempnode.cflag=1;
                   tempnode.col = nr;
                }
      jj_consume_token(RB);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//读取值（宁林�?
//Record：封装name、value信息，在语义分析过程中作为临时变量使�?
//Factor（）—�?>常数 | 字符串（ “[�? 常数  ”]�?�?
//Factor表示把一个整数，变量，常量，表达式或数组转换成为�?��Record类，
//该类存在两个变量name和value。name存储名字，value存�?
  final public Record Factor() throws ParseException {
 /*@bgen(jjtree) Factor */
        SimpleNode jjtn000 = new SimpleNode(JJTFACTOR);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);String name,value="";
        Token node;
        int D=0;
        MyNode tempnode;
        int row=-1,col=-1;
        int rl,cl;
        String temp="",lon="";
        Record r;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONSTANT:
        node = jj_consume_token(CONSTANT);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                name=node.image;
                value=node.image;
                {if (true) return new Record(name,value);}
        break;
      case LC:
        jj_consume_token(LC);
        r = Expression();
        jj_consume_token(RC);
                                jjtree.closeNodeScope(jjtn000, true);
                                jjtc000 = false;
                               //表达�?
                {if (true) return r;}
        break;
      case IDENTIFIER:
        node = jj_consume_token(IDENTIFIER);
                name=node.image;
                tempnode=myNodeList.getNode(name);//从符号表里找到name变量，并把name的全部信息赋给tempnode变量

        label_8:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case LM:
            ;
            break;
          default:
            jj_la1[15] = jj_gen;
            break label_8;
          }
          jj_consume_token(LM);
          node = jj_consume_token(CONSTANT);
                D++;
                if(D==1)
                {
                    row=Integer.parseInt(node.image);//把整型对象Integer转换成基本数据类型int�?
                }
                else if(D==2)
                {
                        col=Integer.parseInt(node.image);
                }
          jj_consume_token(RM);
        }
                if(D==1)
                {
                    if(!myNodeList.isExientence(name)||(myNodeList.getNode(name)).D!=1)
                   {
                        String s = "number "+node.beginLine+" Array "+name+" is undefined";// 数组没有定义，报�?
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                   }
                   if(row>=tempnode.row)
                   {
                           String s = "number "+node.beginLine+" Index out of array!! "+name;//越界报错
                           JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                        }
//四元�?
                   value=tempnode.a[row]+"";
                   temp="T"+(ncount);
                   ncount++;
                   count++;
                   QTTable.addQTInfo(new QTInfo(count,"*",row+"",4+"",temp));//获取数组的入口地�?
                   lon=temp;
                        temp="T"+ncount;
                        ncount++;
                        count++;
                    QTTable.addQTInfo(new QTInfo(count,"=[]",name+"["+lon+"]","-",temp));//变址取数
                }
                else if(D==2)
                {
                    if(!myNodeList.isExientence(name)||(myNodeList.getNode(name)).D!=2)
                   {

                        String s = "number "+node.beginLine+" Array "+name+" is undefined";
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                   }
                    if(row>=tempnode.row)
                        {
                           String s = "number "+node.beginLine+" Row Index out of array!! "+name;
                           JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                        }
                        if(col>=tempnode.col)
                        {
                           String s = "number "+node.beginLine+" Col Index out of array!! "+name;
                           JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                        }
                        value=tempnode.b[row][col]+"";
                        cl=tempnode.col;//c1表示二维数组的列长度
                temp="T"+(ncount);//临时变量下标，初始�?�?
                    ncount++;
                    count++;//四元式标�?
                    QTTable.addQTInfo(new QTInfo(count,"*",row+"",cl+"",temp));//获取数组的入口地�?
                    lon=temp;//�?��标记
                    temp="T"+(ncount);
                    ncount++;
                    count++;
                    QTTable.addQTInfo(new QTInfo(count,"+",lon,col+"",temp));//更新temp标记
                    lon=temp;//�?��标记
                    temp="T"+(ncount);
                    ncount++;
                    count++;
                    QTTable.addQTInfo(new QTInfo(count,"*",lon,4+"",temp));//找到位置
                    lon=temp;
                        temp="T"+ncount;
                        ncount++;
                        count++;
                    QTTable.addQTInfo(new QTInfo(count,"=[]",name+"["+lon+"]","-",temp)); //变址取数

                }
                else if(D==0)
                {
                         if(!myNodeList.isExientence(name)||(myNodeList.getNode(name)).D!=0)
                    {
                        String s = "number "+node.beginLine+" variable "+name+" is undefined";
                        JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                   }
                  value=tempnode.result+"";
                }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
                if(tempnode.D==0)
                {//常数
                        {if (true) return new Record(tempnode.name,value);}
                }
                else
                {//数组
                        {if (true) return new Record(temp,value);}  //返回数组的temp和�?
                }
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

//赋�?语句（王鹤淳�?
  final public void assignment() throws ParseException {
 /*@bgen(jjtree) assignment */
        SimpleNode jjtn000 = new SimpleNode(JJTASSIGNMENT);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token t;
        Token id;
        Token node;
        String idenfier; //被赋值对�?
        Record middle;
        String symbol;
        int result;
        MyNode tempnode=null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        id = jj_consume_token(IDENTIFIER);
                idenfier=id.image;
                if(!myNodeList.isExientence(idenfier)){
                                String s = "variable \u005c""+idenfier+"\u005c" doesn't exist."
                                +"\u005cnwrong number "+id.beginLine;
                                JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                        }
                tempnode=myNodeList.getNode(idenfier);//获取对象的引�?
                if(tempnode.type=="char"|tempnode.type=="short"){
                        String s = "variable type is not  right"
                                +"\u005cnwrong number "+id.beginLine;
                                JOptionPane.showMessageDialog(null,s,"error", JOptionPane.ERROR_MESSAGE);

                }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ASSIGNMENT:
          jj_consume_token(ASSIGNMENT);
          middle = Expression();
                count++;
                QTTable.addQTInfo(new QTInfo(count,"=",middle.getName(),"_",idenfier));
                tempnode.result=Integer.parseInt(middle.getValue());
          break;
        case PLUS:
        case MINUS:
        case MULTIPLY:
        case DIVIDE:
        case REMAINDER:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PLUS:
            node = jj_consume_token(PLUS);
            break;
          case MINUS:
            node = jj_consume_token(MINUS);
            break;
          case MULTIPLY:
            node = jj_consume_token(MULTIPLY);
            break;
          case DIVIDE:
            node = jj_consume_token(DIVIDE);
            break;
          case REMAINDER:
            node = jj_consume_token(REMAINDER);
            break;
          default:
            jj_la1[17] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
                symbol=node.image;
          jj_consume_token(ASSIGNMENT);
          middle = Expression();
                count++;
                QTTable.addQTInfo(new QTInfo(count,symbol,idenfier,middle.getName(),idenfier));
                if(symbol.equals("+")){
                        tempnode.result+=Integer.parseInt(middle.getValue());//更新数�?
                }else if(symbol.equals("-")){
                        tempnode.result+=Integer.parseInt(middle.getValue());//更新数�?
                }else if(symbol.equals("*")){
                        tempnode.result*=Integer.parseInt(middle.getValue());//更新数�?
                }else{
                        tempnode.result/=Integer.parseInt(middle.getValue());//更新数�?
                }
          break;
        case SELFPLUS:
          jj_consume_token(SELFPLUS);
                count++;
                QTTable.addQTInfo(new QTInfo(count,"+",idenfier,"1",idenfier));
                tempnode.result+=1;//更新数�?

          break;
        case SELFMINUS:
          jj_consume_token(SELFMINUS);
                count++;
                tempnode.result-=1;//更新数�?
                QTTable.addQTInfo(new QTInfo(count,"-",idenfier,"1",idenfier));
          break;
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SEMICOLON:
          jj_consume_token(SEMICOLON);
          break;
        case DOT:
          jj_consume_token(DOT);
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case SELFPLUS:
        jj_consume_token(SELFPLUS);
        id = jj_consume_token(IDENTIFIER);
                idenfier=id.image;
                count++;
                QTTable.addQTInfo(new QTInfo(count,"+",idenfier,"1",idenfier));
        jj_consume_token(SEMICOLON);
        break;
      case SELFMINUS:
        jj_consume_token(SELFMINUS);
        id = jj_consume_token(IDENTIFIER);
                idenfier=id.image;
                count++;
                QTTable.addQTInfo(new QTInfo(count,"-",idenfier,"1",idenfier));
        jj_consume_token(SEMICOLON);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//〈条件语句�?�?if〈条件�?〈语句块〉（郝金强）
  final public void If() throws ParseException {
           /*@bgen(jjtree) If */
   SimpleNode jjtn000 = new SimpleNode(JJTIF);
   boolean jjtc000 = true;
   jjtree.openNodeScope(jjtn000);int j1, j2=0, j3;
    try {
      jj_consume_token(IF);
      jj_consume_token(LC);
      Condition();
      jj_consume_token(RC);
   count++;
   j1=count;
   QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(j1)+"#"));//if假出口，target用j1#代替

      SentenceBlock();
   count++;
   QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(j2)+"#"));//�?��语句执行完毕之后，添加跳转语句，target用J2#代替
   QTTable.replaceFirst(String.valueOf(j1)+"#",String.valueOf(count+1)+"");
  //将数回填到刚才if的假出口，将j1#用count+1替换

      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ELSEIF:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_9;
        }
        jj_consume_token(ELSEIF);
        jj_consume_token(LC);
        Condition();
        jj_consume_token(RC);
   count++;
   j3=count;
   QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(j3)+"#"));//else假出�?target用j3#代替

        SentenceBlock();
   count++;
       QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(j2)+"#"));//else里的�?��语句执行完毕之后，添加跳转四元式，target用J2#代替
   QTTable.replaceFirst(String.valueOf(j3)+"#",String.valueOf(count+1)+"");//回填到elseif的假出口，将j3#用count+1代替

      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
        SentenceBlock();
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  QTTable.replaceAll(String.valueOf(j2)+"#",String.valueOf(count+1)+"");//将所有的无条件跳转语句块的j2#替换为当前的count+1

    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//switch条件语句（郝金强�?
  final public void Switch() throws ParseException {
 /*@bgen(jjtree) Switch */
SimpleNode jjtn000 = new SimpleNode(JJTSWITCH);
boolean jjtc000 = true;
jjtree.openNodeScope(jjtn000);Token node;
int j1=0;
int j2;
int next;
Record idenfier;//标识�?
Record con;
    try {
      jj_consume_token(SWITCH);
         j2=-1;
      jj_consume_token(LC);
      idenfier = Expression();
      jj_consume_token(RC);
      jj_consume_token(LB);
      label_10:
      while (true) {
        jj_consume_token(CASE);
        QTTable.replaceFirst(String.valueOf(j1)+"#",String.valueOf(count+1));
        con = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"J=",idenfier.getName(),con.getName(),String.valueOf(next+1)));
        count++;
        j1=count;
        QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(j1)+"#"));//假出口，target用j1#标记

        jj_consume_token(COLON);
        SentenceBlock();
        count++;
        QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(j2)+"#"));//跳转，target用j2#标记

        jj_consume_token(BREAK);
        jj_consume_token(SEMICOLON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CASE:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_10;
        }
      }
      jj_consume_token(DEFAULT1);
        QTTable.replaceFirst(String.valueOf(j1)+"#",String.valueOf(count+1));//回填，将j1#用当前count+1替换
        next=count+1;
      jj_consume_token(COLON);
      SentenceBlock();
      jj_consume_token(BREAK);
        count++;
        QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(count+1)));//结束语句

      jj_consume_token(SEMICOLON);
      jj_consume_token(RB);
  jjtree.closeNodeScope(jjtn000, true);
  jjtc000 = false;
        QTTable.replaceAll(String.valueOf(j2)+"#",String.valueOf(count+1)+"");//回填，将�?��的j2#用当前的count+1替换

    } catch (Throwable jjte000) {
  if (jjtc000) {
    jjtree.clearNodeScope(jjtn000);
    jjtc000 = false;
  } else {
    jjtree.popNode();
  }
  if (jjte000 instanceof RuntimeException) {
    {if (true) throw (RuntimeException)jjte000;}
  }
  if (jjte000 instanceof ParseException) {
    {if (true) throw (ParseException)jjte000;}
  }
  {if (true) throw (Error)jjte000;}
    } finally {
  if (jjtc000) {
    jjtree.closeNodeScope(jjtn000, true);
  }
    }
  }

//do_while语句（程虹翔�?
  final public void do_while() throws ParseException {
 /*@bgen(jjtree) do_while */
        SimpleNode jjtn000 = new SimpleNode(JJTDO_WHILE);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);Token node;
        int next;
        int dofirst;
    try {
      jj_consume_token(DO);
                //记住do的第�?��语句
                dofirst=count+1;
      SentenceBlock();
      jj_consume_token(WHILE);
      jj_consume_token(LC);
      While_Condition();
        //条件成立跳转到循环体的第�?��语句
                QTTable.replaceAll("-2#",String.valueOf(dofirst));
      jj_consume_token(RC);
      jj_consume_token(SEMICOLON);
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
                next=count+1;
                //�?��条件不成立跳出循环体即下�?��语句
                QTTable.replaceAll("0#",String.valueOf(next));
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//while语句（程虹翔�?
  final public void While() throws ParseException {
 /*@bgen(jjtree) While */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token node;
  int j1;
  int j2;
  int next;
  int next1;
  int wh;
    try {
      jj_consume_token(WHILE);
      jj_consume_token(LC);
        next1=count+1;
      While_Condition();
      jj_consume_token(RC);
        wh=count+1;
        //进入循环�?
        QTTable.replaceAll("-2#",String.valueOf(wh));
        //将while条件不成立的做一个标�?
        QTTable.replaceAll("0#",String.valueOf(wh)+"&");
      SentenceBlock();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        count++;
        next=count+1;
        QTTable.replaceAll(String.valueOf(wh)+"&",String.valueOf(next));
        //循环结束跳转返回判断条件是否成立
        QTTable.addQTInfo(new QTInfo(count,"J","_","_",String.valueOf(next1)));
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//while中的条件判断语句（王鹤淳�?
  final public void While_Condition() throws ParseException {
 /*@bgen(jjtree) While_Condition */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILE_CONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token node;
  Record result;
  Record middle;
  int j=0;
  int j1;
  int j2;
  int j3=-2;
  String symbol;
    try {
      result = Expression();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LOWER:
        node = jj_consume_token(LOWER);
        break;
      case GREAT:
        node = jj_consume_token(GREAT);
        break;
      case GREATE:
        node = jj_consume_token(GREATE);
        break;
      case LOWERW:
        node = jj_consume_token(LOWERW);
        break;
      case EQUAL:
        node = jj_consume_token(EQUAL);
        break;
      case UNEQUAL:
        node = jj_consume_token(UNEQUAL);
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        symbol=node.image;
      middle = Expression();
        count++;
    con=count;
        QTTable.addQTInfo(new QTInfo(count,"j"+symbol,result.getName(),middle.getName(),String.valueOf(con)+"#"));
        count++;
        QTTable.addQTInfo(new QTInfo(count,"j","_","_",String.valueOf(j)+"#"));
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
          ;
          break;
        default:
          jj_la1[25] = jj_gen;
          break label_11;
        }
        jj_consume_token(AND);
        //继续判断
        j1=count+1;
        QTTable.replaceFirst(String.valueOf(con)+"#",String.valueOf(j1));
        While_Condition();
      }
        //条件成立做一个标�?
        QTTable.replaceFirst(String.valueOf(con)+"#",String.valueOf(j3)+"#");
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OR:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_12;
        }
        jj_consume_token(OR);
        //and条件都不成立的话跳转到or
        j2=count+1;
        QTTable.replaceAll(String.valueOf(j)+"#",String.valueOf(j2));
        While_Condition();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//for循环语句（杨帅）
  final public void For() throws ParseException {
 /*@bgen(jjtree) For */
         SimpleNode jjtn000 = new SimpleNode(JJTFOR);
         boolean jjtc000 = true;
         jjtree.openNodeScope(jjtn000);int j1;
         int j2;
         Token node=null,node1=null;
    try {
      jj_consume_token(FOR);
      jj_consume_token(LC);
      assignment();
                 j1=count+1;
      While_Condition();
         //写两条四元式
                j++;
                QTTable.replaceAll("-2#",j+"-2#");//真出口，替换�?��，把-2#替换�?-2#
                QTTable.replaceAll("0#",j+"0#");//假出口，替换�?��，把0#替换�?0#
                j2=count+1;
      jj_consume_token(SEMICOLON);
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          node = jj_consume_token(IDENTIFIER);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case SELFPLUS:
            node1 = jj_consume_token(SELFPLUS);
            break;
          case SELFMINUS:
            node1 = jj_consume_token(SELFMINUS);
            break;
          default:
            jj_la1[27] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        case DOT:
          jj_consume_token(DOT);
          break;
        default:
          jj_la1[28] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DOT:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[29] = jj_gen;
          break label_13;
        }
      }
      jj_consume_token(RC);
      SentenceBlock();
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
         //写语句块语句的四元式	
        {//执行++�?-
                count++;//对四元式序号的操�?
                if(node1.image=="++"){
                QTTable.addQTInfo(new QTInfo(count,"+",node.image,"1",node.image));
                }//添加�?��四元式，函数里的参数是一个QTInfo对象，new新建�?��四元式，类里面也�?个参数，
                          //count是四元式标号�?+的四元式相当于是+1的那种四元式
                else{
                QTTable.addQTInfo(new QTInfo(count,"-",node.image,"1",node.image));
                }
                count++;//标号+1
                QTTable.addQTInfo(new QTInfo(count,"j","_","_",String.valueOf(j1)));//无条件跳转语�?
        }
                QTTable.replaceAll(j+"-2#",String.valueOf(j2));//替换j2的�?
                QTTable.replaceAll(j+"0#",String.valueOf(count+1));//替换语句�?2#代表真出口，0#代表假出�?
                                                                   //替换count+1的�?
                j--;
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//〈条件�?→（〈表达式〉�?关系符�?〈表达式〉）（程虹翔�?
  final public int Condition() throws ParseException {
 /*@bgen(jjtree) Condition */
  SimpleNode jjtn000 = new SimpleNode(JJTCONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token node;
  int next;
  Record result;
  Record middle;
    try {
      //	Expression()(Relate() Expression())
        result = Expression();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LOWER:
        node = jj_consume_token(LOWER);
        middle = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"j<",result.getName(),middle.getName(),String.valueOf(next+1)));
        break;
      case GREAT:
        node = jj_consume_token(GREAT);
        middle = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"j>",result.getName(),middle.getName(),String.valueOf(next+1)));
        break;
      case GREATE:
        node = jj_consume_token(GREATE);
        middle = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"j>=",result.getName(),middle.getName(),String.valueOf(next+1)));
        break;
      case LOWERW:
        node = jj_consume_token(LOWERW);
        middle = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"j<=",result.getName(),middle.getName(),String.valueOf(next+1)));
        break;
      case EQUAL:
        node = jj_consume_token(EQUAL);
        middle = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"j=",result.getName(),middle.getName(),String.valueOf(next+1)));
        break;
      case UNEQUAL:
        node = jj_consume_token(UNEQUAL);
        middle = Expression();
        count++;
        next=count+1;
        QTTable.addQTInfo(new QTInfo(count,"j!=",result.getName(),middle.getName(),String.valueOf(next+1)));
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
     jjtree.closeNodeScope(jjtn000, true);
     jjtc000 = false;
        {if (true) return next;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//加减运算表达式（郝金强）
  final public Record Expression() throws ParseException {
 /*@bgen(jjtree) Expression */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token node;
  Record rValue;//存储前一个Term()信息
  Record middleR;//存储后一个Term()信息
  String result=null;//前一个Term()的�?
  String middle=null;//后一个Term()的�?
  String middletemp=null;//后一个Term()的名�?
  String temp="";//前一个Term()的名�?
  String preStr=null;
  String pretem="";//第一个临时变量名�?
  int perStep=0;
    try {
      rValue = Term();
        temp=rValue.getName();
        result=rValue.getValue();
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
        case MINUS:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_14;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          jj_consume_token(PLUS);
        if(preStr!=null){
                pretem="T"+(ncount-1);//前一个临时变�?
        }
          middleR = Term();
                 //读取后一个Term()
        middletemp=middleR.getName();
        middle=middleR.getValue();
        count++;//四元式下标自�?
        temp="T"+(ncount);//临时变量
        //为下�?��临时变量做准�?
        ncount++;
        if(preStr==null){
                QTTable.addQTInfo(new QTInfo(count,"+",rValue.getName(),middletemp,temp));

        }else{
                //把开始�?和中间�?放在临时变量�?
                QTTable.addQTInfo(new QTInfo(count,"+",pretem,middletemp,temp));
        }
        //存储计算结果的�?
        result=Integer.parseInt(result)+Integer.parseInt(middle)+"";
        preStr=temp;
          break;
        case MINUS:
          jj_consume_token(MINUS);
        if(preStr!=null){
                pretem="T"+(ncount-1);
        }
          middleR = Term();
        middletemp=middleR.getName();
        middle=middleR.getValue();
        count++;
        temp="T"+ncount;
        ncount++;
        if(preStr==null){
                //把开始�?和中间�?放在临时变量�?
                QTTable.addQTInfo(new QTInfo(count,"-",rValue.getName(),middletemp,temp));
        }else{
                //把开始�?和中间�?放在临时变量�?
                QTTable.addQTInfo(new QTInfo(count,"-",pretem,middletemp,temp));
        }
        result=Integer.parseInt(result)-Integer.parseInt(middle)+"";
        preStr=temp;
          break;
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        rValue=new Record(temp,result);
        {if (true) return rValue;}//�?��返回表达式的值即�?

    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//乘除运算表达式（宁林�?
  final public Record Term() throws ParseException {
 /*@bgen(jjtree) Term */
  SimpleNode jjtn000 = new SimpleNode(JJTTERM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token node;
  Record rValue=null;//存储前一个Term()信息
  Record MiddleR=null;//存储后一个Term()信息
  String result;//前一个Term()的�?
  String middle;//后一个Term()的�?
  String middletemp;
  String middleName;
  String temp="";
  String symbol="";//运算�?
  String preStr=null;
  String pretem=null;
    try {
      rValue = Factor();
        temp=rValue.getName();
        result=rValue.getValue();
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULTIPLY:
        case DIVIDE:
        case REMAINDER:
          ;
          break;
        default:
          jj_la1[33] = jj_gen;
          break label_15;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULTIPLY:
          node = jj_consume_token(MULTIPLY);
          break;
        case DIVIDE:
          node = jj_consume_token(DIVIDE);
          break;
        case REMAINDER:
          node = jj_consume_token(REMAINDER);
          break;
        default:
          jj_la1[34] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        symbol=node.image;
        if(preStr!=null){
                pretem="T"+(ncount-1);
        }
        MiddleR = Factor();
        middletemp=MiddleR.getName();
        middle=MiddleR.getValue();
        count++;
            temp="T"+ncount;
            ncount++;
            if(preStr==null){

                        //把开始�?和中间�?放在临时变量�?
                        QTTable.addQTInfo(new QTInfo(count,symbol,rValue.getName(),middletemp,temp));
                }else{
                        //把开始�?和中间�?放在临时变量�?
                        QTTable.addQTInfo(new QTInfo(count,symbol,pretem,middletemp,temp));
                }
            result=Integer.parseInt(result)*Integer.parseInt(middle)+"";
            preStr=temp;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        rValue=new Record(temp,result);
        {if (true) return rValue;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//类型定义
  final public String Type() throws ParseException {
 /*@bgen(jjtree) Type */
SimpleNode jjtn000 = new SimpleNode(JJTTYPE);
boolean jjtc000 = true;
jjtree.openNodeScope(jjtn000);Token node;
String type;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FLOAT:
        node = jj_consume_token(FLOAT);
        break;
      case LONG:
        node = jj_consume_token(LONG);
        break;
      case INT:
        node = jj_consume_token(INT);
        break;
      case SHORT:
        node = jj_consume_token(SHORT);
        break;
      case CHAR:
        node = jj_consume_token(CHAR);
        break;
      case DOUBLE:
        node = jj_consume_token(DOUBLE);
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          type=node.image;
          {if (true) return type;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public CompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[36];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x201,0x1fa39000,0x1fa39000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2000,0x4000,0x80000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1f800000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x80000600,0x80000600,0x800000,0x0,0x800,0x8000000,0x800000,0x0,0x800,0x8000000,0x8000000,0x82200000,0x82200000,0x8000000,0x800000,0x80200000,0x1f0,0xff0,0x18000000,0x80000600,0x0,0x0,0x0,0x3f000,0x40000,0x80000,0x600,0x88000000,0x88000000,0x3f000,0x30,0x30,0x1c0,0x1c0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x2,0x2,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Compiler(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compiler(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compiler(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compiler(CompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[67];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 36; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 67; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
