/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.1 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package parser;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.channels.FileChannel;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.1 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
@SuppressWarnings("all")
public class SimpleNode implements Node {
  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Compiler parser;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(Compiler p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }
  
  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }
  public void clearnTxt() throws IOException
  {
	  String filename = "Grammertree.txt";
	  RandomAccessFile rf = new RandomAccessFile(filename, "rw");
	  FileChannel fc = rf.getChannel();
	  fc.truncate(0);
  }
  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return CompilerTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) throws IOException {
    //System.out.println(toString(prefix));
	  FileWriter GrammerTree = new FileWriter("Grammertree.txt",true);
	  GrammerTree.write(toString(prefix)+"\n");
	  GrammerTree.close();
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
    	  SimpleNode n = (SimpleNode)children[i];
    	  if (n != null) {
    		  n.dump(prefix + " ");
    	  }
      }
    }
  }
}

/* JavaCC - OriginalChecksum=625bd7dfd7567d0417ae1d61ec4bec00 (do not edit this line) */
/* JavaCC - OriginalChecksum=9fdfa24533e176415ebfe95a25ef84f2 (do not edit this line) */
